server:
  port: 3000
# datasoure默认使用JDBC
spring:
  rabbitmq:
          host: localhost
          port: 5672
          username: guest
          password: guest
#  zipkin:
#    base-url: http://localhost:9411
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ENC(gc16brBHPNq27HsjaULgKGq00Rz6ZUji)
    url: jdbc:mysql://106.14.69.75:3309/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false

cloud:
  auth:
    clientId: ENC(Ho5VxMWMMIzfIEE8/WxVzA==)
    clientSecret: ENC(Ho5VxMWMMIzfIEE8/WxVzA==)
    scope: server
  social:
    qq:
      providerId: qq
      clientId: ENC(jYTHlVSN8p2C3KrLz40H7JJYZcQs3SAK)
      clientSecret: ENC(DmTyBXeNFG7Z6pooPCtDUMcI1MYTiO3ldaEOuVWmOTpgDVmyGMsI42hz6OM+0pEE)

urls:
  anon:
    - /social
    - /signin
    - /signup
    - /mobile/token

#logging:
#  config: classpath:logback-spring.xml

